com.azure.spring.ai.vectorstore.cosmosdb.autoconfigure.CosmosDBVectorStoreAutoConfiguration=
com.azure.spring.ai.vectorstore.cosmosdb.autoconfigure.CosmosDBVectorStoreAutoConfiguration.ConditionalOnClass=com.azure.cosmos.CosmosAsyncClient,com.azure.spring.ai.vectorstore.cosmosdb.CosmosDBVectorStore,org.springframework.ai.embedding.EmbeddingModel
